"""Application-specific exception types for the itero package.

Defines a lightweight, coherent error hierarchy for geometry validation,
plotting configuration, and rendering failures.
"""

class PolygonIterError(Exception):
    """Base exception for all application errors."""

# Polygon-related errors
class InvalidNumSidesError(PolygonIterError): ...
class InvalidRatioError(PolygonIterError): ...
class InvalidIterationsError(PolygonIterError): ...
class DegeneratePolygonError(PolygonIterError): ...
class InvalidBackendError(PolygonIterError): ...
class ExcessiveMemoryUsageError(PolygonIterError): ...

# Plot-related errors
class InvalidAlphaError(PolygonIterError): ...
class InvalidColorMapError(PolygonIterError): ...
class InvalidColorError(PolygonIterError): ...
class InvalidColorSpecError(PolygonIterError): ...
class RenderingError(PolygonIterError): ...
class InvalidFigureSizeError(PolygonIterError): ...